### ISSUE TITLE
[V2]: TODO for Moodle 405

### ISSUE THREAD

**Issue by jxn-30** [jxn-30/better-moodle#517]
# High priority

# Medium priority
- [x] Better-Moodle Drawers throw error `Uncaught TypeError: can't access property "classList", headerContent is null` on open. (fixed in 024299f)

# Low priority
- [x] external link icon being cut off (fixed in bcbad44)
![grafik](https://github.com/user-attachments/assets/992a2429-ab1b-4bfa-a179-a9e4d77258c1)
- [x] search icon in settings being cut off  (fixed in bcbad44)
![grafik](https://github.com/user-attachments/assets/874cd531-583f-43f6-b320-18be3234d6dd)

**Comment by jxn-30** [comment]
UzL now runs on 405, so we will see Issues live when developing V2 further.
